spring:
  application:
    name: spring-ai-rag-expert
  ai:
    openai:
      #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
app:
  vector-store:
    path: tmp/vectorstore.json
    documents-to-load:
      - 'classpath:/movies500Trimmed.csv'
