spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
app:
  vector-store:
    path: tmp/vectorstore.json
    documents-to-load:
      - 'classpath:/movies500.csv'

