### Answer the question
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "Is butterfly looks like the butter that can fly?"
}

### Capital of the state
POST http://localhost:8080/capital
Content-Type: application/json

{
  "stateOrCountry": "Ukraine"
}

### Capital with info
POST http://localhost:8080/capitalWithInfo
Content-Type: application/json

{
  "stateOrCountry": "Lithuania"
}

### Capital with info - JSON output
POST http://localhost:8080/capitalWithInfo
Content-Type: application/json
Accept: application/json

{
  "stateOrCountry": "Poland"
}

