### Answer the question
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "What is the movie `Avengers: Infinity War` about?"
}

### Avatar question
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "How many movies about Avatar exists?"
}

### Avengers
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "How many parts of movie Avengers?"
}

### Avengers movie count
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "How many movies about the Avengers?"
}

### Spider Man description
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "What do you know about the movie `Spider-Man: No Way Home`?"
}

### Spider Man describe
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "Describe the movie `Spider-Man: No Way Home`?"
}


### Spider Man duration
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "What is the duration of the movie `Spider-Man: No Way Home`?"
}
